foreground              #c9d1d9
background              #161b22
selection_foreground    #010409
selection_background    #d29922

cursor                  #58a6ff
cursor_text_color       #010409

url_color               #f0883e

active_border_color     #58a6ff
inactive_border_color   #21262d
bell_border_color       #f85149

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #010409
active_tab_background   #388bfd
inactive_tab_foreground #8b949e
inactive_tab_background #161b22
tab_bar_background      #010409

mark1_foreground #010409
mark1_background #58a6ff
mark2_foreground #010409
mark2_background #3fb950
mark3_foreground #010409
mark3_background #f0883e

color0 #21262d
color8 #b1bac4

color1 #f85149
color9 #f85149

color2  #58a6ff
color10 #388bfd

color3  #f0883e
color11 #d2a8ff

color4  #3fb950
color12 #d29922

color5  #388bfd
color13 #bc8cff

color6  #d29922
color14 #d2a8ff

color7  #8b949e
color15 #c9d1d9
